# This workflow uses actions that are not certified by GitHub.
name: Deploy to Pages
on:
  push:
    branches: ["master", "gh-pages"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: head
          bundler-cache: true
      - name: Build org-ruby pages
        run: bundle exec rake github:pages
      - name: Extracting css
        run: bundle exec rougify style monokai > public/monokai.css
      - name: Upload public folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
          retention-days: 30
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy org-ruby pages
        uses: actions/deploy-pages@v4
